version: 1.0.{build}
os: Visual Studio 2015
configuration:
- Release
- Debug
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  verbosity: minimal
after_build:
- 7z a OBeautifulCode.TypeRepresentation.zip %APPVEYOR_BUILD_FOLDER%\OBeautifulCode.TypeRepresentation\bin\%CONFIGURATION%\*.* -r
- ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/NaosProject/Naos.Powershell/master/Build/Nuget-Functions.ps1', "$($env:appveyor_build_folder)\Nuget-Functions.ps1")
- ps: . "$($env:appveyor_build_folder)\Nuget-Functions.ps1"
- ps: $version = Nuget-CreatePreReleaseSupportedVersion -version $env:appveyor_build_version -branchName $env:appveyor_repo_branch
- ps: nuget pack "$($env:appveyor_build_folder)\OBeautifulCode.TypeRepresentation\OBeautifulCode.TypeRepresentation.csproj" -Version $version -Prop Platform=AnyCPU
artifacts:
- path: OBeautifulCode.TypeRepresentation.zip
- path: '*.nupkg'
- path: Nuget-Functions.ps1
deploy:
  provider: NuGet
  api_key:
    secure: aUaOAaFmJX9VJGINuxJ86ljfbXzi6I748PR0zL8VdZElrdh7C0sbPoFRKl8eciDY
  skip_symbols: true
  artifact: /.*\.nupkg/