// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CultureKindExtensions.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Type
{
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Globalization;
    using static System.FormattableString;

    /// <summary>
    /// Extension methods on <see cref="CultureKind"/>.
    /// </summary>
    public static class CultureKindExtensions
    {
        private static readonly Dictionary<CultureKind, string> CultureKindToCultureNameMap =
            new Dictionary<CultureKind, string>
            {
                { CultureKind.AfarDjibouti, @"aa-DJ" },
                { CultureKind.AfarEritrea, @"aa-ER" },
                { CultureKind.AfarEthiopia, @"aa-ET" },
                { CultureKind.AfrikaansNamibia, @"af-NA" },
                { CultureKind.AfrikaansSouthAfrica, @"af-ZA" },
                { CultureKind.AghemCameroon, @"agq-CM" },
                { CultureKind.AkanGhana, @"ak-GH" },
                { CultureKind.AmharicEthiopia, @"am-ET" },
                { CultureKind.ArabicWorld, @"ar-001" },
                { CultureKind.ArabicUnitedArabEmirates, @"ar-AE" },
                { CultureKind.ArabicBahrain, @"ar-BH" },
                { CultureKind.ArabicDjibouti, @"ar-DJ" },
                { CultureKind.ArabicAlgeria, @"ar-DZ" },
                { CultureKind.ArabicEgypt, @"ar-EG" },
                { CultureKind.ArabicEritrea, @"ar-ER" },
                { CultureKind.ArabicIsrael, @"ar-IL" },
                { CultureKind.ArabicIraq, @"ar-IQ" },
                { CultureKind.ArabicJordan, @"ar-JO" },
                { CultureKind.ArabicComoros, @"ar-KM" },
                { CultureKind.ArabicKuwait, @"ar-KW" },
                { CultureKind.ArabicLebanon, @"ar-LB" },
                { CultureKind.ArabicLibya, @"ar-LY" },
                { CultureKind.ArabicMorocco, @"ar-MA" },
                { CultureKind.ArabicMauritania, @"ar-MR" },
                { CultureKind.ArabicOman, @"ar-OM" },
                { CultureKind.ArabicPalestinianAuthority, @"ar-PS" },
                { CultureKind.ArabicQatar, @"ar-QA" },
                { CultureKind.ArabicSaudiArabia, @"ar-SA" },
                { CultureKind.ArabicSudan, @"ar-SD" },
                { CultureKind.ArabicSomalia, @"ar-SO" },
                { CultureKind.ArabicSouthSudan, @"ar-SS" },
                { CultureKind.ArabicSyria, @"ar-SY" },
                { CultureKind.ArabicChad, @"ar-TD" },
                { CultureKind.ArabicTunisia, @"ar-TN" },
                { CultureKind.ArabicYemen, @"ar-YE" },
                { CultureKind.MapucheChile, @"arn-CL" },
                { CultureKind.AssameseIndia, @"as-IN" },
                { CultureKind.AsuTanzania, @"asa-TZ" },
                { CultureKind.AsturianSpain, @"ast-ES" },
                { CultureKind.AzerbaijaniCyrillicAzerbaijan, @"az-Cyrl-AZ" },
                { CultureKind.AzerbaijaniLatinAzerbaijan, @"az-Latn-AZ" },
                { CultureKind.BashkirRussia, @"ba-RU" },
                { CultureKind.BasaaCameroon, @"bas-CM" },
                { CultureKind.BelarusianBelarus, @"be-BY" },
                { CultureKind.BembaZambia, @"bem-ZM" },
                { CultureKind.BenaTanzania, @"bez-TZ" },
                { CultureKind.BulgarianBulgaria, @"bg-BG" },
                { CultureKind.EdoNigeria, @"bin-NG" },
                { CultureKind.BamanankanLatinMali, @"bm-Latn-ML" },
                { CultureKind.BanglaBangladesh, @"bn-BD" },
                { CultureKind.BengaliIndia, @"bn-IN" },
                { CultureKind.TibetanChina, @"bo-CN" },
                { CultureKind.TibetanIndia, @"bo-IN" },
                { CultureKind.BretonFrance, @"br-FR" },
                { CultureKind.BodoIndia, @"brx-IN" },
                { CultureKind.BosnianCyrillicBosniaandHerzegovina, @"bs-Cyrl-BA" },
                { CultureKind.BosnianLatinBosniaHerzegovina, @"bs-Latn-BA" },
                { CultureKind.BlinEritrea, @"byn-ER" },
                { CultureKind.CatalanAndorra, @"ca-AD" },
                { CultureKind.CatalanCatalan, @"ca-ES" },
                { CultureKind.ValencianSpain, @"ca-ES-valencia" },
                { CultureKind.CatalanFrance, @"ca-FR" },
                { CultureKind.CatalanItaly, @"ca-IT" },
                { CultureKind.ChakmaChakmaBangladesh, @"ccp-Cakm-BD" },
                { CultureKind.ChakmaChakmaIndia, @"ccp-Cakm-IN" },
                { CultureKind.ChechenRussia, @"ce-RU" },
                { CultureKind.CebuanoLatinPhilippines, @"ceb-Latn-PH" },
                { CultureKind.ChigaUganda, @"cgg-UG" },
                { CultureKind.CherokeeCherokeeUnitedStates, @"chr-Cher-US" },
                { CultureKind.CorsicanFrance, @"co-FR" },
                { CultureKind.CzechCzechia, @"cs-CZ" },
                { CultureKind.ChurchSlavicRussia, @"cu-RU" },
                { CultureKind.WelshUnitedKingdom, @"cy-GB" },
                { CultureKind.DanishDenmark, @"da-DK" },
                { CultureKind.DanishGreenland, @"da-GL" },
                { CultureKind.TaitaKenya, @"dav-KE" },
                { CultureKind.GermanAustria, @"de-AT" },
                { CultureKind.GermanBelgium, @"de-BE" },
                { CultureKind.GermanSwitzerland, @"de-CH" },
                { CultureKind.GermanGermany, @"de-DE" },
                { CultureKind.GermanItaly, @"de-IT" },
                { CultureKind.GermanLiechtenstein, @"de-LI" },
                { CultureKind.GermanLuxembourg, @"de-LU" },
                { CultureKind.ZarmaNiger, @"dje-NE" },
                { CultureKind.LowerSorbianGermany, @"dsb-DE" },
                { CultureKind.DualaCameroon, @"dua-CM" },
                { CultureKind.DivehiMaldives, @"dv-MV" },
                { CultureKind.JolaFonyiSenegal, @"dyo-SN" },
                { CultureKind.DzongkhaBhutan, @"dz-BT" },
                { CultureKind.EmbuKenya, @"ebu-KE" },
                { CultureKind.EweGhana, @"ee-GH" },
                { CultureKind.EweTogo, @"ee-TG" },
                { CultureKind.GreekCyprus, @"el-CY" },
                { CultureKind.GreekGreece, @"el-GR" },
                { CultureKind.EnglishWorld, @"en-001" },
                { CultureKind.EnglishCaribbean, @"en-029" },
                { CultureKind.EnglishEurope, @"en-150" },
                { CultureKind.EnglishUnitedArabEmirates, @"en-AE" },
                { CultureKind.EnglishAntiguaBarbuda, @"en-AG" },
                { CultureKind.EnglishAnguilla, @"en-AI" },
                { CultureKind.EnglishAmericanSamoa, @"en-AS" },
                { CultureKind.EnglishAustria, @"en-AT" },
                { CultureKind.EnglishAustralia, @"en-AU" },
                { CultureKind.EnglishBarbados, @"en-BB" },
                { CultureKind.EnglishBelgium, @"en-BE" },
                { CultureKind.EnglishBurundi, @"en-BI" },
                { CultureKind.EnglishBermuda, @"en-BM" },
                { CultureKind.EnglishBahamas, @"en-BS" },
                { CultureKind.EnglishBotswana, @"en-BW" },
                { CultureKind.EnglishBelize, @"en-BZ" },
                { CultureKind.EnglishCanada, @"en-CA" },
                { CultureKind.EnglishCocosKeelingIslands, @"en-CC" },
                { CultureKind.EnglishSwitzerland, @"en-CH" },
                { CultureKind.EnglishCookIslands, @"en-CK" },
                { CultureKind.EnglishCameroon, @"en-CM" },
                { CultureKind.EnglishChristmasIsland, @"en-CX" },
                { CultureKind.EnglishCyprus, @"en-CY" },
                { CultureKind.EnglishGermany, @"en-DE" },
                { CultureKind.EnglishDenmark, @"en-DK" },
                { CultureKind.EnglishDominica, @"en-DM" },
                { CultureKind.EnglishEritrea, @"en-ER" },
                { CultureKind.EnglishFinland, @"en-FI" },
                { CultureKind.EnglishFiji, @"en-FJ" },
                { CultureKind.EnglishFalklandIslands, @"en-FK" },
                { CultureKind.EnglishMicronesia, @"en-FM" },
                { CultureKind.EnglishUnitedKingdom, @"en-GB" },
                { CultureKind.EnglishGrenada, @"en-GD" },
                { CultureKind.EnglishGuernsey, @"en-GG" },
                { CultureKind.EnglishGhana, @"en-GH" },
                { CultureKind.EnglishGibraltar, @"en-GI" },
                { CultureKind.EnglishGambia, @"en-GM" },
                { CultureKind.EnglishGuam, @"en-GU" },
                { CultureKind.EnglishGuyana, @"en-GY" },
                { CultureKind.EnglishHongKongSar, @"en-HK" },
                { CultureKind.EnglishIndonesia, @"en-ID" },
                { CultureKind.EnglishIreland, @"en-IE" },
                { CultureKind.EnglishIsrael, @"en-IL" },
                { CultureKind.EnglishIsleofMan, @"en-IM" },
                { CultureKind.EnglishIndia, @"en-IN" },
                { CultureKind.EnglishBritishIndianOceanTerritory, @"en-IO" },
                { CultureKind.EnglishJersey, @"en-JE" },
                { CultureKind.EnglishJamaica, @"en-JM" },
                { CultureKind.EnglishKenya, @"en-KE" },
                { CultureKind.EnglishKiribati, @"en-KI" },
                { CultureKind.EnglishStKittsNevis, @"en-KN" },
                { CultureKind.EnglishCaymanIslands, @"en-KY" },
                { CultureKind.EnglishStLucia, @"en-LC" },
                { CultureKind.EnglishLiberia, @"en-LR" },
                { CultureKind.EnglishLesotho, @"en-LS" },
                { CultureKind.EnglishMadagascar, @"en-MG" },
                { CultureKind.EnglishMarshallIslands, @"en-MH" },
                { CultureKind.EnglishMacaoSar, @"en-MO" },
                { CultureKind.EnglishNorthernMarianaIslands, @"en-MP" },
                { CultureKind.EnglishMontserrat, @"en-MS" },
                { CultureKind.EnglishMalta, @"en-MT" },
                { CultureKind.EnglishMauritius, @"en-MU" },
                { CultureKind.EnglishMalawi, @"en-MW" },
                { CultureKind.EnglishMalaysia, @"en-MY" },
                { CultureKind.EnglishNamibia, @"en-NA" },
                { CultureKind.EnglishNorfolkIsland, @"en-NF" },
                { CultureKind.EnglishNigeria, @"en-NG" },
                { CultureKind.EnglishNetherlands, @"en-NL" },
                { CultureKind.EnglishNauru, @"en-NR" },
                { CultureKind.EnglishNiue, @"en-NU" },
                { CultureKind.EnglishNewZealand, @"en-NZ" },
                { CultureKind.EnglishPapuaNewGuinea, @"en-PG" },
                { CultureKind.EnglishPhilippines, @"en-PH" },
                { CultureKind.EnglishPakistan, @"en-PK" },
                { CultureKind.EnglishPitcairnIslands, @"en-PN" },
                { CultureKind.EnglishPuertoRico, @"en-PR" },
                { CultureKind.EnglishPalau, @"en-PW" },
                { CultureKind.EnglishRwanda, @"en-RW" },
                { CultureKind.EnglishSolomonIslands, @"en-SB" },
                { CultureKind.EnglishSeychelles, @"en-SC" },
                { CultureKind.EnglishSudan, @"en-SD" },
                { CultureKind.EnglishSweden, @"en-SE" },
                { CultureKind.EnglishSingapore, @"en-SG" },
                { CultureKind.EnglishStHelenaAscensionTristandaCunha, @"en-SH" },
                { CultureKind.EnglishSlovenia, @"en-SI" },
                { CultureKind.EnglishSierraLeone, @"en-SL" },
                { CultureKind.EnglishSouthSudan, @"en-SS" },
                { CultureKind.EnglishSintMaarten, @"en-SX" },
                { CultureKind.EnglishEswatini, @"en-SZ" },
                { CultureKind.EnglishTurksCaicosIslands, @"en-TC" },
                { CultureKind.EnglishTokelau, @"en-TK" },
                { CultureKind.EnglishTonga, @"en-TO" },
                { CultureKind.EnglishTrinidadTobago, @"en-TT" },
                { CultureKind.EnglishTuvalu, @"en-TV" },
                { CultureKind.EnglishTanzania, @"en-TZ" },
                { CultureKind.EnglishUganda, @"en-UG" },
                { CultureKind.EnglishUSOutlyingIslands, @"en-UM" },
                { CultureKind.EnglishUnitedStates, @"en-US" },
                { CultureKind.EnglishStVincentGrenadines, @"en-VC" },
                { CultureKind.EnglishBritishVirginIslands, @"en-VG" },
                { CultureKind.EnglishUSVirginIslands, @"en-VI" },
                { CultureKind.EnglishVanuatu, @"en-VU" },
                { CultureKind.EnglishSamoa, @"en-WS" },
                { CultureKind.EnglishSouthAfrica, @"en-ZA" },
                { CultureKind.EnglishZambia, @"en-ZM" },
                { CultureKind.EnglishZimbabwe, @"en-ZW" },
                { CultureKind.EsperantoWorld, @"eo-001" },
                { CultureKind.SpanishLatinAmerica, @"es-419" },
                { CultureKind.SpanishArgentina, @"es-AR" },
                { CultureKind.SpanishBolivia, @"es-BO" },
                { CultureKind.SpanishBrazil, @"es-BR" },
                { CultureKind.SpanishBelize, @"es-BZ" },
                { CultureKind.SpanishChile, @"es-CL" },
                { CultureKind.SpanishColombia, @"es-CO" },
                { CultureKind.SpanishCostaRica, @"es-CR" },
                { CultureKind.SpanishCuba, @"es-CU" },
                { CultureKind.SpanishDominicanRepublic, @"es-DO" },
                { CultureKind.SpanishEcuador, @"es-EC" },
                { CultureKind.SpanishSpainInternationalSort, @"es-ES" },
                { CultureKind.SpanishEquatorialGuinea, @"es-GQ" },
                { CultureKind.SpanishGuatemala, @"es-GT" },
                { CultureKind.SpanishHonduras, @"es-HN" },
                { CultureKind.SpanishMexico, @"es-MX" },
                { CultureKind.SpanishNicaragua, @"es-NI" },
                { CultureKind.SpanishPanama, @"es-PA" },
                { CultureKind.SpanishPeru, @"es-PE" },
                { CultureKind.SpanishPhilippines, @"es-PH" },
                { CultureKind.SpanishPuertoRico, @"es-PR" },
                { CultureKind.SpanishParaguay, @"es-PY" },
                { CultureKind.SpanishElSalvador, @"es-SV" },
                { CultureKind.SpanishUnitedStates, @"es-US" },
                { CultureKind.SpanishUruguay, @"es-UY" },
                { CultureKind.SpanishVenezuela, @"es-VE" },
                { CultureKind.EstonianEstonia, @"et-EE" },
                { CultureKind.BasqueBasque, @"eu-ES" },
                { CultureKind.EwondoCameroon, @"ewo-CM" },
                { CultureKind.PersianIran, @"fa-IR" },
                { CultureKind.FulahLatinBurkinaFaso, @"ff-Latn-BF" },
                { CultureKind.FulahLatinCameroon, @"ff-Latn-CM" },
                { CultureKind.FulahLatinGhana, @"ff-Latn-GH" },
                { CultureKind.FulahLatinGambia, @"ff-Latn-GM" },
                { CultureKind.FulahLatinGuinea, @"ff-Latn-GN" },
                { CultureKind.FulahLatinGuineaBissau, @"ff-Latn-GW" },
                { CultureKind.FulahLatinLiberia, @"ff-Latn-LR" },
                { CultureKind.FulahLatinMauritania, @"ff-Latn-MR" },
                { CultureKind.FulahLatinNiger, @"ff-Latn-NE" },
                { CultureKind.FulahLatinNigeria, @"ff-Latn-NG" },
                { CultureKind.FulahLatinSierraLeone, @"ff-Latn-SL" },
                { CultureKind.FulahLatinSenegal, @"ff-Latn-SN" },
                { CultureKind.FinnishFinland, @"fi-FI" },
                { CultureKind.FilipinoPhilippines, @"fil-PH" },
                { CultureKind.FaroeseDenmark, @"fo-DK" },
                { CultureKind.FaroeseFaroeIslands, @"fo-FO" },
                { CultureKind.FrenchCaribbean, @"fr-029" },
                { CultureKind.FrenchBelgium, @"fr-BE" },
                { CultureKind.FrenchBurkinaFaso, @"fr-BF" },
                { CultureKind.FrenchBurundi, @"fr-BI" },
                { CultureKind.FrenchBenin, @"fr-BJ" },
                { CultureKind.FrenchStBarthlemy, @"fr-BL" },
                { CultureKind.FrenchCanada, @"fr-CA" },
                { CultureKind.FrenchCongoDrc, @"fr-CD" },
                { CultureKind.FrenchCentralAfricanRepublic, @"fr-CF" },
                { CultureKind.FrenchCongo, @"fr-CG" },
                { CultureKind.FrenchSwitzerland, @"fr-CH" },
                { CultureKind.FrenchCtedIvoire, @"fr-CI" },
                { CultureKind.FrenchCameroon, @"fr-CM" },
                { CultureKind.FrenchDjibouti, @"fr-DJ" },
                { CultureKind.FrenchAlgeria, @"fr-DZ" },
                { CultureKind.FrenchFrance, @"fr-FR" },
                { CultureKind.FrenchGabon, @"fr-GA" },
                { CultureKind.FrenchFrenchGuiana, @"fr-GF" },
                { CultureKind.FrenchGuinea, @"fr-GN" },
                { CultureKind.FrenchGuadeloupe, @"fr-GP" },
                { CultureKind.FrenchEquatorialGuinea, @"fr-GQ" },
                { CultureKind.FrenchHaiti, @"fr-HT" },
                { CultureKind.FrenchComoros, @"fr-KM" },
                { CultureKind.FrenchLuxembourg, @"fr-LU" },
                { CultureKind.FrenchMorocco, @"fr-MA" },
                { CultureKind.FrenchMonaco, @"fr-MC" },
                { CultureKind.FrenchStMartin, @"fr-MF" },
                { CultureKind.FrenchMadagascar, @"fr-MG" },
                { CultureKind.FrenchMali, @"fr-ML" },
                { CultureKind.FrenchMartinique, @"fr-MQ" },
                { CultureKind.FrenchMauritania, @"fr-MR" },
                { CultureKind.FrenchMauritius, @"fr-MU" },
                { CultureKind.FrenchNewCaledonia, @"fr-NC" },
                { CultureKind.FrenchNiger, @"fr-NE" },
                { CultureKind.FrenchFrenchPolynesia, @"fr-PF" },
                { CultureKind.FrenchStPierreMiquelon, @"fr-PM" },
                { CultureKind.FrenchRunion, @"fr-RE" },
                { CultureKind.FrenchRwanda, @"fr-RW" },
                { CultureKind.FrenchSeychelles, @"fr-SC" },
                { CultureKind.FrenchSenegal, @"fr-SN" },
                { CultureKind.FrenchSyria, @"fr-SY" },
                { CultureKind.FrenchChad, @"fr-TD" },
                { CultureKind.FrenchTogo, @"fr-TG" },
                { CultureKind.FrenchTunisia, @"fr-TN" },
                { CultureKind.FrenchVanuatu, @"fr-VU" },
                { CultureKind.FrenchWallisFutuna, @"fr-WF" },
                { CultureKind.FrenchMayotte, @"fr-YT" },
                { CultureKind.FriulianItaly, @"fur-IT" },
                { CultureKind.WesternFrisianNetherlands, @"fy-NL" },
                { CultureKind.IrishIreland, @"ga-IE" },
                { CultureKind.ScottishGaelicUnitedKingdom, @"gd-GB" },
                { CultureKind.GalicianGalician, @"gl-ES" },
                { CultureKind.GuaraniParaguay, @"gn-PY" },
                { CultureKind.SwissGermanSwitzerland, @"gsw-CH" },
                { CultureKind.AlsatianFrance, @"gsw-FR" },
                { CultureKind.SwissGermanLiechtenstein, @"gsw-LI" },
                { CultureKind.GujaratiIndia, @"gu-IN" },
                { CultureKind.GusiiKenya, @"guz-KE" },
                { CultureKind.ManxIsleofMan, @"gv-IM" },
                { CultureKind.HausaLatinGhana, @"ha-Latn-GH" },
                { CultureKind.HausaLatinNiger, @"ha-Latn-NE" },
                { CultureKind.HausaLatinNigeria, @"ha-Latn-NG" },
                { CultureKind.HawaiianUnitedStates, @"haw-US" },
                { CultureKind.HebrewIsrael, @"he-IL" },
                { CultureKind.HindiIndia, @"hi-IN" },
                { CultureKind.CroatianBosniaHerzegovina, @"hr-BA" },
                { CultureKind.CroatianCroatia, @"hr-HR" },
                { CultureKind.UpperSorbianGermany, @"hsb-DE" },
                { CultureKind.HungarianHungary, @"hu-HU" },
                { CultureKind.ArmenianArmenia, @"hy-AM" },
                { CultureKind.InterlinguaWorld, @"ia-001" },
                { CultureKind.IbibioNigeria, @"ibb-NG" },
                { CultureKind.IndonesianIndonesia, @"id-ID" },
                { CultureKind.IgboNigeria, @"ig-NG" },
                { CultureKind.YiChina, @"ii-CN" },
                { CultureKind.IcelandicIceland, @"is-IS" },
                { CultureKind.ItalianSwitzerland, @"it-CH" },
                { CultureKind.ItalianItaly, @"it-IT" },
                { CultureKind.ItalianSanMarino, @"it-SM" },
                { CultureKind.ItalianVaticanCity, @"it-VA" },
                { CultureKind.InuktitutSyllabicsCanada, @"iu-Cans-CA" },
                { CultureKind.InuktitutLatinCanada, @"iu-Latn-CA" },
                { CultureKind.JapaneseJapan, @"ja-JP" },
                { CultureKind.NgombaCameroon, @"jgo-CM" },
                { CultureKind.MachameTanzania, @"jmc-TZ" },
                { CultureKind.JavaneseJavaneseIndonesia, @"jv-Java-ID" },
                { CultureKind.JavaneseIndonesia, @"jv-Latn-ID" },
                { CultureKind.GeorgianGeorgia, @"ka-GE" },
                { CultureKind.KabyleAlgeria, @"kab-DZ" },
                { CultureKind.KambaKenya, @"kam-KE" },
                { CultureKind.MakondeTanzania, @"kde-TZ" },
                { CultureKind.KabuverdianuCaboVerde, @"kea-CV" },
                { CultureKind.KoyraChiiniMali, @"khq-ML" },
                { CultureKind.KikuyuKenya, @"ki-KE" },
                { CultureKind.KazakhKazakhstan, @"kk-KZ" },
                { CultureKind.KakoCameroon, @"kkj-CM" },
                { CultureKind.KalaallisutGreenland, @"kl-GL" },
                { CultureKind.KalenjinKenya, @"kln-KE" },
                { CultureKind.KhmerCambodia, @"km-KH" },
                { CultureKind.KannadaIndia, @"kn-IN" },
                { CultureKind.KoreanNorthKorea, @"ko-KP" },
                { CultureKind.KoreanKorea, @"ko-KR" },
                { CultureKind.KonkaniIndia, @"kok-IN" },
                { CultureKind.KanuriNigeria, @"kr-Latn-NG" },
                { CultureKind.KashmiriPersoArabic, @"ks-Arab-IN" },
                { CultureKind.KashmiriDevanagari, @"ks-Deva-IN" },
                { CultureKind.ShambalaTanzania, @"ksb-TZ" },
                { CultureKind.BafiaCameroon, @"ksf-CM" },
                { CultureKind.ColognianGermany, @"ksh-DE" },
                { CultureKind.CentralKurdishIraq, @"ku-Arab-IQ" },
                { CultureKind.KurdishPersoArabicIran, @"ku-Arab-IR" },
                { CultureKind.CornishUnitedKingdom, @"kw-GB" },
                { CultureKind.KyrgyzKyrgyzstan, @"ky-KG" },
                { CultureKind.LatinWorld, @"la-001" },
                { CultureKind.LangiTanzania, @"lag-TZ" },
                { CultureKind.LuxembourgishLuxembourg, @"lb-LU" },
                { CultureKind.GandaUganda, @"lg-UG" },
                { CultureKind.LakotaUnitedStates, @"lkt-US" },
                { CultureKind.LingalaAngola, @"ln-AO" },
                { CultureKind.LingalaCongoDrc, @"ln-CD" },
                { CultureKind.LingalaCentralAfricanRepublic, @"ln-CF" },
                { CultureKind.LingalaCongo, @"ln-CG" },
                { CultureKind.LaoLaos, @"lo-LA" },
                { CultureKind.NorthernLuriIraq, @"lrc-IQ" },
                { CultureKind.NorthernLuriIran, @"lrc-IR" },
                { CultureKind.LithuanianLithuania, @"lt-LT" },
                { CultureKind.LubaKatangaCongoDrc, @"lu-CD" },
                { CultureKind.LuoKenya, @"luo-KE" },
                { CultureKind.LuyiaKenya, @"luy-KE" },
                { CultureKind.LatvianLatvia, @"lv-LV" },
                { CultureKind.MasaiKenya, @"mas-KE" },
                { CultureKind.MasaiTanzania, @"mas-TZ" },
                { CultureKind.MeruKenya, @"mer-KE" },
                { CultureKind.MorisyenMauritius, @"mfe-MU" },
                { CultureKind.MalagasyMadagascar, @"mg-MG" },
                { CultureKind.MakhuwaMeettoMozambique, @"mgh-MZ" },
                { CultureKind.MetaCameroon, @"mgo-CM" },
                { CultureKind.MaoriNewZealand, @"mi-NZ" },
                { CultureKind.MacedonianNorthMacedonia, @"mk-MK" },
                { CultureKind.MalayalamIndia, @"ml-IN" },
                { CultureKind.MongolianMongolia, @"mn-MN" },
                { CultureKind.MongolianTraditionalMongolianChina, @"mn-Mong-CN" },
                { CultureKind.MongolianTraditionalMongolianMongolia, @"mn-Mong-MN" },
                { CultureKind.ManipuriIndia, @"mni-IN" },
                { CultureKind.MohawkMohawk, @"moh-CA" },
                { CultureKind.MarathiIndia, @"mr-IN" },
                { CultureKind.MalayBrunei, @"ms-BN" },
                { CultureKind.MalayMalaysia, @"ms-MY" },
                { CultureKind.MalaySingapore, @"ms-SG" },
                { CultureKind.MalteseMalta, @"mt-MT" },
                { CultureKind.MundangCameroon, @"mua-CM" },
                { CultureKind.BurmeseMyanmar, @"my-MM" },
                { CultureKind.MazanderaniIran, @"mzn-IR" },
                { CultureKind.NamaNamibia, @"naq-NA" },
                { CultureKind.NorwegianBokmlNorway, @"nb-NO" },
                { CultureKind.NorwegianBokmlSvalbardJanMayen, @"nb-SJ" },
                { CultureKind.NorthNdebeleZimbabwe, @"nd-ZW" },
                { CultureKind.LowGermanGermany, @"nds-DE" },
                { CultureKind.LowGermanNetherlands, @"nds-NL" },
                { CultureKind.NepaliIndia, @"ne-IN" },
                { CultureKind.NepaliNepal, @"ne-NP" },
                { CultureKind.DutchAruba, @"nl-AW" },
                { CultureKind.DutchBelgium, @"nl-BE" },
                { CultureKind.DutchBonaireSintEustatiusandSaba, @"nl-BQ" },
                { CultureKind.DutchCuraao, @"nl-CW" },
                { CultureKind.DutchNetherlands, @"nl-NL" },
                { CultureKind.DutchSuriname, @"nl-SR" },
                { CultureKind.DutchSintMaarten, @"nl-SX" },
                { CultureKind.KwasioCameroon, @"nmg-CM" },
                { CultureKind.NorwegianNynorskNorway, @"nn-NO" },
                { CultureKind.NgiemboonCameroon, @"nnh-CM" },
                { CultureKind.NkoGuinea, @"nqo-GN" },
                { CultureKind.SouthNdebeleSouthAfrica, @"nr-ZA" },
                { CultureKind.SesothosaLeboaSouthAfrica, @"nso-ZA" },
                { CultureKind.NuerSouthSudan, @"nus-SS" },
                { CultureKind.NyankoleUganda, @"nyn-UG" },
                { CultureKind.OccitanFrance, @"oc-FR" },
                { CultureKind.OromoEthiopia, @"om-ET" },
                { CultureKind.OromoKenya, @"om-KE" },
                { CultureKind.OdiaIndia, @"or-IN" },
                { CultureKind.OsseticGeorgia, @"os-GE" },
                { CultureKind.OsseticRussia, @"os-RU" },
                { CultureKind.PunjabiPakistan, @"pa-Arab-PK" },
                { CultureKind.PunjabiIndia, @"pa-IN" },
                { CultureKind.PapiamentoCaribbean, @"pap-029" },
                { CultureKind.PolishPoland, @"pl-PL" },
                { CultureKind.PrussianWorld, @"prg-001" },
                { CultureKind.DariAfghanistan, @"prs-AF" },
                { CultureKind.PashtoAfghanistan, @"ps-AF" },
                { CultureKind.PashtoPakistan, @"ps-PK" },
                { CultureKind.PortugueseAngola, @"pt-AO" },
                { CultureKind.PortugueseBrazil, @"pt-BR" },
                { CultureKind.PortugueseSwitzerland, @"pt-CH" },
                { CultureKind.PortugueseCaboVerde, @"pt-CV" },
                { CultureKind.PortugueseEquatorialGuinea, @"pt-GQ" },
                { CultureKind.PortugueseGuineaBissau, @"pt-GW" },
                { CultureKind.PortugueseLuxembourg, @"pt-LU" },
                { CultureKind.PortugueseMacaoSar, @"pt-MO" },
                { CultureKind.PortugueseMozambique, @"pt-MZ" },
                { CultureKind.PortuguesePortugal, @"pt-PT" },
                { CultureKind.PortugueseSoTomPrncipe, @"pt-ST" },
                { CultureKind.PortugueseTimorLeste, @"pt-TL" },
                { CultureKind.KicheGuatemala, @"quc-Latn-GT" },
                { CultureKind.QuechuaBolivia, @"quz-BO" },
                { CultureKind.QuechuaEcuador, @"quz-EC" },
                { CultureKind.QuechuaPeru, @"quz-PE" },
                { CultureKind.RomanshSwitzerland, @"rm-CH" },
                { CultureKind.RundiBurundi, @"rn-BI" },
                { CultureKind.RomanianMoldova, @"ro-MD" },
                { CultureKind.RomanianRomania, @"ro-RO" },
                { CultureKind.RomboTanzania, @"rof-TZ" },
                { CultureKind.RussianBelarus, @"ru-BY" },
                { CultureKind.RussianKyrgyzstan, @"ru-KG" },
                { CultureKind.RussianKazakhstan, @"ru-KZ" },
                { CultureKind.RussianMoldova, @"ru-MD" },
                { CultureKind.RussianRussia, @"ru-RU" },
                { CultureKind.RussianUkraine, @"ru-UA" },
                { CultureKind.KinyarwandaRwanda, @"rw-RW" },
                { CultureKind.RwaTanzania, @"rwk-TZ" },
                { CultureKind.SanskritIndia, @"sa-IN" },
                { CultureKind.SakhaRussia, @"sah-RU" },
                { CultureKind.SamburuKenya, @"saq-KE" },
                { CultureKind.SanguTanzania, @"sbp-TZ" },
                { CultureKind.SindhiPakistan, @"sd-Arab-PK" },
                { CultureKind.SindhiDevanagariIndia, @"sd-Deva-IN" },
                { CultureKind.SamiNorthernFinland, @"se-FI" },
                { CultureKind.SamiNorthernNorway, @"se-NO" },
                { CultureKind.SamiNorthernSweden, @"se-SE" },
                { CultureKind.SenaMozambique, @"seh-MZ" },
                { CultureKind.KoyraboroSenniMali, @"ses-ML" },
                { CultureKind.SangoCentralAfricanRepublic, @"sg-CF" },
                { CultureKind.TachelhitLatinMorocco, @"shi-Latn-MA" },
                { CultureKind.TachelhitTifinaghMorocco, @"shi-Tfng-MA" },
                { CultureKind.SinhalaSriLanka, @"si-LK" },
                { CultureKind.SlovakSlovakia, @"sk-SK" },
                { CultureKind.SlovenianSlovenia, @"sl-SI" },
                { CultureKind.SamiSouthernNorway, @"sma-NO" },
                { CultureKind.SamiSouthernSweden, @"sma-SE" },
                { CultureKind.SamiLuleNorway, @"smj-NO" },
                { CultureKind.SamiLuleSweden, @"smj-SE" },
                { CultureKind.SamiInariFinland, @"smn-FI" },
                { CultureKind.SamiSkoltFinland, @"sms-FI" },
                { CultureKind.ShonaLatinZimbabwe, @"sn-Latn-ZW" },
                { CultureKind.SomaliDjibouti, @"so-DJ" },
                { CultureKind.SomaliEthiopia, @"so-ET" },
                { CultureKind.SomaliKenya, @"so-KE" },
                { CultureKind.SomaliSomalia, @"so-SO" },
                { CultureKind.AlbanianAlbania, @"sq-AL" },
                { CultureKind.AlbanianNorthMacedonia, @"sq-MK" },
                { CultureKind.AlbanianKosovo, @"sq-XK" },
                { CultureKind.SerbianCyrillicBosniaandHerzegovina, @"sr-Cyrl-BA" },
                { CultureKind.SerbianCyrillicMontenegro, @"sr-Cyrl-ME" },
                { CultureKind.SerbianCyrillicSerbia, @"sr-Cyrl-RS" },
                { CultureKind.SerbianCyrillicKosovo, @"sr-Cyrl-XK" },
                { CultureKind.SerbianLatinBosniaHerzegovina, @"sr-Latn-BA" },
                { CultureKind.SerbianLatinMontenegro, @"sr-Latn-ME" },
                { CultureKind.SerbianLatinSerbia, @"sr-Latn-RS" },
                { CultureKind.SerbianLatinKosovo, @"sr-Latn-XK" },
                { CultureKind.SiSwatiEswatini, @"ss-SZ" },
                { CultureKind.SiSwatiSouthAfrica, @"ss-ZA" },
                { CultureKind.SahoEritrea, @"ssy-ER" },
                { CultureKind.SesothoLesotho, @"st-LS" },
                { CultureKind.SesothoSouthAfrica, @"st-ZA" },
                { CultureKind.SwedishlandIslands, @"sv-AX" },
                { CultureKind.SwedishFinland, @"sv-FI" },
                { CultureKind.SwedishSweden, @"sv-SE" },
                { CultureKind.KiswahiliCongoDrc, @"sw-CD" },
                { CultureKind.KiswahiliKenya, @"sw-KE" },
                { CultureKind.KiswahiliTanzania, @"sw-TZ" },
                { CultureKind.KiswahiliUganda, @"sw-UG" },
                { CultureKind.SyriacSyria, @"syr-SY" },
                { CultureKind.TamilIndia, @"ta-IN" },
                { CultureKind.TamilSriLanka, @"ta-LK" },
                { CultureKind.TamilMalaysia, @"ta-MY" },
                { CultureKind.TamilSingapore, @"ta-SG" },
                { CultureKind.TeluguIndia, @"te-IN" },
                { CultureKind.TesoKenya, @"teo-KE" },
                { CultureKind.TesoUganda, @"teo-UG" },
                { CultureKind.TajikCyrillicTajikistan, @"tg-Cyrl-TJ" },
                { CultureKind.ThaiThailand, @"th-TH" },
                { CultureKind.TigrinyaEritrea, @"ti-ER" },
                { CultureKind.TigrinyaEthiopia, @"ti-ET" },
                { CultureKind.TigreEritrea, @"tig-ER" },
                { CultureKind.TurkmenTurkmenistan, @"tk-TM" },
                { CultureKind.SetswanaBotswana, @"tn-BW" },
                { CultureKind.SetswanaSouthAfrica, @"tn-ZA" },
                { CultureKind.TonganTonga, @"to-TO" },
                { CultureKind.TurkishCyprus, @"tr-CY" },
                { CultureKind.TurkishTurkey, @"tr-TR" },
                { CultureKind.XitsongaSouthAfrica, @"ts-ZA" },
                { CultureKind.TatarRussia, @"tt-RU" },
                { CultureKind.TasawaqNiger, @"twq-NE" },
                { CultureKind.CentralAtlasTamazightArabicMorocco, @"tzm-Arab-MA" },
                { CultureKind.CentralAtlasTamazightLatinAlgeria, @"tzm-Latn-DZ" },
                { CultureKind.CentralAtlasTamazightLatinMorocco, @"tzm-Latn-MA" },
                { CultureKind.CentralAtlasTamazightTifinaghMorocco, @"tzm-Tfng-MA" },
                { CultureKind.UyghurChina, @"ug-CN" },
                { CultureKind.UkrainianUkraine, @"uk-UA" },
                { CultureKind.UrduIndia, @"ur-IN" },
                { CultureKind.UrduPakistan, @"ur-PK" },
                { CultureKind.UzbekPersoArabicAfghanistan, @"uz-Arab-AF" },
                { CultureKind.UzbekCyrillicUzbekistan, @"uz-Cyrl-UZ" },
                { CultureKind.UzbekLatinUzbekistan, @"uz-Latn-UZ" },
                { CultureKind.VaiLatinLiberia, @"vai-Latn-LR" },
                { CultureKind.VaiVaiLiberia, @"vai-Vaii-LR" },
                { CultureKind.VendaSouthAfrica, @"ve-ZA" },
                { CultureKind.VietnameseVietnam, @"vi-VN" },
                { CultureKind.VolapkWorld, @"vo-001" },
                { CultureKind.VunjoTanzania, @"vun-TZ" },
                { CultureKind.WalserSwitzerland, @"wae-CH" },
                { CultureKind.WolayttaEthiopia, @"wal-ET" },
                { CultureKind.WolofSenegal, @"wo-SN" },
                { CultureKind.IsiXhosaSouthAfrica, @"xh-ZA" },
                { CultureKind.SogaUganda, @"xog-UG" },
                { CultureKind.YangbenCameroon, @"yav-CM" },
                { CultureKind.YiddishWorld, @"yi-001" },
                { CultureKind.YorubaBenin, @"yo-BJ" },
                { CultureKind.YorubaNigeria, @"yo-NG" },
                { CultureKind.StandardMoroccanTamazightTifinaghMorocco, @"zgh-Tfng-MA" },
                { CultureKind.ChineseSimplifiedChina, @"zh-CN" },
                { CultureKind.ChineseSimplifiedHanHongKongSar, @"zh-Hans-HK" },
                { CultureKind.ChineseSimplifiedHanMacaoSar, @"zh-Hans-MO" },
                { CultureKind.ChineseTraditionalHongKongSar, @"zh-HK" },
                { CultureKind.ChineseTraditionalMacaoSar, @"zh-MO" },
                { CultureKind.ChineseSimplifiedSingapore, @"zh-SG" },
                { CultureKind.ChineseTraditionalTaiwan, @"zh-TW" },
                { CultureKind.IsiZuluSouthAfrica, @"zu-ZA" },
            };

        private static readonly ConcurrentDictionary<CultureKind, CultureInfo> CachedCultureKindToCultureInfoMap =
            new ConcurrentDictionary<CultureKind, CultureInfo>(
                new[]
                {
                    new KeyValuePair<CultureKind, CultureInfo>(CultureKind.Invariant, CultureInfo.InvariantCulture),
                });

        /// <summary>
        /// Gets the culture name associated with a specified <see cref="CultureKind"/>.
        /// </summary>
        /// <remarks>
        /// Dictionary entries generated via unit test.
        /// </remarks>
        /// <param name="cultureKind">The culture kind.</param>
        /// <returns>
        /// The culture name associated with a specified <see cref="CultureKind"/>.
        /// </returns>
        public static string ToCultureName(
            this CultureKind cultureKind)
        {
            if (cultureKind == CultureKind.Unknown)
            {
                throw new ArgumentOutOfRangeException(Invariant($"{nameof(cultureKind)} is {nameof(CultureKind)}.{nameof(CultureKind.Unknown)}"));
            }

            if (!CultureKindToCultureNameMap.ContainsKey(cultureKind))
            {
                throw new NotSupportedException(Invariant($"This {nameof(CultureKind)} is not supported: {cultureKind}."));
            }

            var result = CultureKindToCultureNameMap[cultureKind];

            return result;
        }

        /// <summary>
        /// Gets the <see cref="CultureInfo"/> associated with a specified <see cref="CultureKind"/>.
        /// </summary>
        /// <param name="cultureKind">The culture kind.</param>
        /// <returns>
        /// The <see cref="CultureInfo"/> associated with a specified <see cref="CultureKind"/>.
        /// </returns>
        public static CultureInfo ToCultureInfo(
            this CultureKind cultureKind)
        {
            if (cultureKind == CultureKind.Unknown)
            {
                throw new ArgumentOutOfRangeException(Invariant($"{nameof(cultureKind)} is {nameof(CultureKind)}.{nameof(CultureKind.Unknown)}"));
            }

            if (CachedCultureKindToCultureInfoMap.ContainsKey(cultureKind))
            {
                return CachedCultureKindToCultureInfoMap[cultureKind];
            }

            var cultureName = cultureKind.ToCultureName();

            var result = new CultureInfo(cultureName);

            CachedCultureKindToCultureInfoMap.TryAdd(cultureKind, result);

            return result;
        }
    }
}
